# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webforum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='topic',
        ),
    ]
